* Kids Believe Gender Stereotypes by Age 10, Global Study Finds
After a six-year study of gender steeotypes, TIMES Heatlth cliams that in almost all societies, gender stereotypes are embeded and influence kids at young age around 10 - 14 at different degrees.
The society as a whole often assigns different gender roles, the influence to the adolescents to act and behave differently. Some are even negative.
Boys with the social expectation to be risk taker, and may try to build up the expectation by fighting, taking durgs and smoking.
While the world shrinks for the girls, with the expectation of staying home at most times.
* Kids everywhere have damaging gender stereotyping set by age 10
The study claims that gender stereotypes influence adolescents negatively.
The result is proven by the following social activities observed:
1. Parents intervene their kids for having relationships with opposite sex in some culture.
2. Dropping out of school is more often amoung girls and under situations like early pregnancy and sexual violence.
3. Boys in some area are found abusing girls with their sexual urge due to these local norm.
Both articles pointed out that gender stereotypes are more oftenly found in the middle and low income families/countries.
Dispite all above, it is still possible for the change of stereotypes, great examples can be found in North America and Europe. The best age range to change the stereotype is early adolescent.
